name: weatherapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  intl: any
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2

  # map permissions
  location: ^4.4.0
  google_maps_flutter: ^2.5.3
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_api_headers: ^1.3.0
  awesome_snackbar_content: ^0.1.0
  weather: ^3.0.0
  units_converter: ^3.0.0
  flutter_localization: ^0.2.0
  geolocator: ^11.0.0
  http: ^0.13.6
  mocktail: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/assets/keys.json